#!/bin/sh

# ttsd 1.0

# DESCRIPTION:
# Some yummy espeak presets to use.

# DEPENDENCIES:
# espeak-ng

opt="-s 173 $2"

case "$1" in
0 ) espeak -v en+f1 -p 54 $opt;;
1 ) espeak -v en-us+f1 -p 62 $opt;;
2 ) espeak -v en+klatt3 -p 27 $opt;;
3 ) espeak -v en-us+klatt2 -p 46 $opt;;
4 ) espeak -v en+m7 -p 86 $opt;;
5 ) espeak -v en-us+klatt2 -p 84 $opt;;
6 ) espeak -v en -p 42 $opt;;
7 ) espeak -v en-us -p 50 $opt;;
8 ) espeak -v en-us -p 80 $opt;;
9 ) espeak -v en-us -p 90 $opt;;
10 ) espeak -v en -p 68 $opt;;
11 ) espeak -v en-us -p 75 $opt;;
* ) 
echo "$0 [voice] [text]";
echo;
echo "voice:";
echo "0 = female 1";
echo "1 = female 2";
echo "2 = male 1";
echo "3 = male 2";
echo "4 = androgynous 1?";
echo "5 = androgynous 2?";
echo "6 = espeak male 1";
echo "7 = espeak male 2";
echo "8 = espeak female 1";
echo "9 = espeak female 2";
echo "10 = espeak androgynous 1";
echo "11 = espeak androgynous 2";;
esac
